### ISSUE TITLE
Make the units in physical space in order to prevent the voxel distortion of the z plane

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#37]
- [ ] Make the units in physical space in order to prevent the voxel distortion of the z plane

**Comment by toekneesunshine** [comment]
Currently, I used the sITK.GetSpacing() command to make properly-sized brains.  An example Plotly for Aut1367 can be seen [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/reveal/html/Aut1367_region_color_spaced.html).  Unfortunately, since our Github page can no longer host additional content, you'll have to download the HTML (click Download and save the page as an HTML, then double click the downloaded HTML).

I've also hosted a copy on an alternate Github page (see [here](https://toekneesunshine.github.io/)).

**Comment by toekneesunshine** [comment]
TODO:  While the above brain image is properly dimensioned, it isn't exactly in millimeters yet (currently, it's some factor of millimeters).

In order to get it in millimeters, I need access to the x resolution/y resolution/z resolution data from ndstore -- on openconnecto.me, those are just data field entries.  However, since the Aut brains are private datasets, I can't actually see those parameters.  If I knew those numbers, I could properly scale each of the points to their relative points in physical space.

**Comment by toekneesunshine** [comment]
Cross referencing inImg.GetSpacing with the level 5 spacing data from http://openconnecto.me/ocp/ca/Aut1367/info/, we see that the sitk command is in fact returning the dimensions in mm.
