### ISSUE TITLE
Figure out how to deal with hierarchical atlas

### ISSUE THREAD

**Issue by mlee156** [NeuroDataDesign/seelviz-f16s17#51]
Figure out how to deal with hierarchical atlas - deliverable is jupyter notebook with our work

**Comment by toekneesunshine** [comment]
Talked to Jovo/Greg about how to do this.  Greg gave us the code for removing individual regions from the atlas.  After a lot of searching, I couldn't find a better CSV version of the ARA (with just the most specific regions that we're interested in).  Since manually parsing 1000 regions and cross referencing them to the atlas hierarchy takes a long time, Jovo recommended that we visualize just the ARA to see if there was a pattern to the atlas hierarchy (eg: intermediary regions are cut off by their subsidiaries).

I wrote an ipynb that takes the atlas region brain and runs through a similar process to generate our atlas region plots after ndstore came back online.  If you turn off the 'tag' for unknown (region ID = 0), you get the annotations.

Code [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/VisualizingAtlas/Visualizing%2Bthe%2BARA%2BRegions.ipynb).  
Visual [here](https://github.com/alee156/cldev/blob/master/Tony/images/dec5/fixedARA.png).  
Plotly [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/VisualizingAtlas/ARA_CCF_ds_10x_region_color_spaced%20(2).html).  
CSV counts [here](https://github.com/NeuroDataDesign/seelviz/blob/gh-pages/Tony/VisualizingAtlas/ARA_CCF2_ds_10XCounts.csv).

**Comment by toekneesunshine** [comment]
Hey @kkutten1 
I've looked at your code [here](https://github.com/neurodata/ndreg/blob/master/doc/ramonifyARA.py), but I still have some questions on how to isolate the most specific layers of the atlas.

Can I meet up with you sometime to go over it?

**Comment by kkutten1** [comment]
@toekneesunshine: Just sent you an email about meeting.

**Comment by toekneesunshine** [comment]
Met with Kwame, who helped me generate the most specific regions of the ARA.  We now dynamically do so during the atlas region graph step by calling the JSON -- I've made the edits on the in the cldev repo, and we're putting it into the pipeline.

**Comment by toekneesunshine** [comment]
Jon and I put this into the latest version of the pipeline.  We gucci.
